import type { Metadata } from "next";
import { Roboto, Sansita } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const sansitaMono = Sansita({
  variable: "--font-sansita-mono",
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Blog JCWDOH01-003",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${sansitaMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
